Repository ClemM10/Exja, pull requests merged in 2020-10, with the labels that each got.

#2 Texte
  Website.md
Labels: Orthographe

#1 Add ex2
  Website.md
Labels: enhancement

#5 exo3
  Website.md
Labels: help wanted

#6 SendinEx4Zip
  Website.md
Labels: enhancement
